# Generated by Django 5.0.1 on 2024-01-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='lat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='lon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
