# Generated by Django 5.0.1 on 2024-01-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junk', '0002_alter_group_name_alter_person_lat_alter_person_lon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/people/'),
        ),
    ]
