# Generated by Django 5.0.1 on 2024-01-26 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junk', '0002_alter_loop_bags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='loop',
        ),
        migrations.AddField(
            model_name='loop',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='junk.day'),
            preserve_default=False,
        ),
    ]
