# Generated by Django 5.0.1 on 2024-01-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junk', '0004_alter_person_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loop',
            name='bags',
            field=models.FloatField(),
        ),
    ]
