# Generated by Django 5.0.1 on 2024-01-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junk', '0005_alter_loop_bags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
